force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpptyTriggerHandlerTestClass.cls
@istest 
public class OpptyTriggerHandlerTestClass {
  
  @istest 
  public static void unitTest1(){
    List<Opportunity> oppList = new List<Opportunity> ();
    List<Position__c> posList = new List<Position__c> ();
    test.startTest();
    oppList = TestUtils.createOpportunity('Oppty for Test', 10);
    posList = TestUtils.createPosition('position for test', 1);
    oppList[0].isprivate = true;
    insert oppList;
    insert posList;
    
    oppList[0].MainCompetitors__c = 'new';
    posList[0].Opportunity__c = oppList[0].id;
    update posList; 
    update opplist;
    system.debug('opp : '+ oppList);
    
    delete oppList[2];
    test.stoptest();
    system.assert(true,true);
  }

}