force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>first name of the candidate</description>
    <externalId>true</externalId>
    <label>First Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CandidateControllerTest.cls
@IsTest
public class CandidateControllerTest{

	static List<Candidate__c> canList = new List<Candidate__c>();
	static List<Position__C> posList = new List<Position__C>();
	static List<Job_Application__c> jaList = new List<Job_Application__c>();

	public static testmethod void testFetchData(){
		canList.add(Utilitycls.createCandidate(0,true));
        canList.add(canList.get(0));
		posList.add(Utilitycls.createPosition('Consultant','mehul jain',true));
		posList.add(Utilitycls.createPosition('Project Manager','Cynthia Capobianco',true));
		jaList.add(Utilitycls.createJA('John0','Consultant',true));
		jaList.add(Utilitycls.createJA('John0','Project Manager',true));
        

		test.startTest();
		System.debug('1'+canList.get(0));
		System.debug('2'+posList.get(0));
		System.debug('3'+jaList.get(0));

        CandidateController testobj = new CandidateController();
		testobj.fetchData();
        Integer i = 0;
        System.debug('size of candwrap'+testobj.mapCandWrapper.get('Jaipur').size());
		for(CandidateController.CandidateWrapper testWrap : testobj.mapCandWrapper.get('Jaipur')){	
            System.assertEquals(canList.get(i).First_Name__c,testWrap.candidateName);
			System.assertEquals(posList.get(i).Hiring_Manager__r.FirstName,testWrap.hiringManagerName);
//			System.assertEquals(jaList.get(i++).Name,testWrap.jobAppName);
            System.debug(canList.get(i).First_Name__c+testWrap.candidateName);
			System.debug(posList.get(i).Hiring_Manager__r.FirstName+testWrap.hiringManagerName);
			System.debug(jaList.get(i++).Name+testWrap.jobAppName);
		}
		test.stopTest();
	}
}