force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email id of the candidate</description>
    <externalId>true</externalId>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>first name of the candidate</description>
    <externalId>true</externalId>
    <label>First Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description>Social Security number</description>
    <label>SSN</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Utilitycls.cls
public class Utilitycls {


	public static Candidate__c createCandidate(Integer i, Boolean isInsert){
		Candidate__c can1 = new Candidate__c();

			can1.First_Name__c = 'John'+i;
			can1.Mobile__c = '999999999'+i;
			can1.Email__c = 'John'+i+'@test.c';
            can1.SSN__c = '678' + i;
            can1.Date_of_Birth__c = date.newInstance(1990,6,5+i);
            can1.City__c = 'Jaipur';
		
        if(isInsert){
            insert can1;
        }
            
        return can1;

	}


	public static Position__c createPosition(String posName, String Hir_mgr, Boolean isInsert){
		Position__c pos1 = new Position__c();
        pos1.Name = posName;
		pos1.Hiring_Manager__r = [SELECT Id, FirstName 
                                  FROM User 
                                  WHERE Name =:Hir_mgr LIMIT 1];
        pos1.Hiring_Manager__c = pos1.Hiring_Manager__r.Id;
        System.debug('hrmng'+pos1.Hiring_Manager__r.FirstName);				// issue
		
        if(isInsert){
            insert pos1;
        }
            
        return pos1;

	}


	public static Job_Application__c createJA(String candName, String posName, Boolean isInsert){
		Job_Application__c ja1 = new Job_Application__c();
		ja1.Candidate__c = [SELECT Id
                                  FROM Candidate__c 
                                  WHERE First_Name__c =:candName LIMIT 1].Id;
		ja1.Position__c = [SELECT Id 
                                  FROM Position__c 
                                  WHERE Name =:posName LIMIT 1].Id;
        

        if(isInsert){
            insert ja1;
        }
         System.debug('ja1name'+ja1.Name);   
        return ja1;

	}

}