force-app/main/default/objects/CFS_Customer__c/CFS_Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CFS_Customer__c/fields/Currently_Borrowed_Items__c.field-meta.xml
<CustomField>
    <fullName>Currently_Borrowed_Items__c</fullName>
    <label>Currently Borrowed Items</label>
    <summaryFilterItems>
        <field>CMS_Customer_Item__c.Status__c</field>
        <operation>equals</operation>
        <value>Borrow</value>
    </summaryFilterItems>
    <summaryForeignKey>CMS_Customer_Item__c.CSF_Customer__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/CFS_Error_Log__c/CFS_Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{0000}</displayFormat>
        <label>Error Logging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CFS_Error_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>40000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CFS_Error_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Code Exception</fullName>
            </value>
            <value>
                <fullName>Integration Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CFS_Item__c/CFS_Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CFS_Item__c/fields/Book_Author__c.field-meta.xml
<CustomField>
    <fullName>Book_Author__c</fullName>
    <label>Book Author</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFS_Item__c/fields/Book_name__c.field-meta.xml
<CustomField>
    <fullName>Book_name__c</fullName>
    <label>Book name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFS_Item__c/fields/Book_Publication__c.field-meta.xml
<CustomField>
    <fullName>Book_Publication__c</fullName>
    <label>Book Publication</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFS_Item__c/fields/CFS_Category__c.field-meta.xml
<CustomField>
    <fullName>CFS_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Biography</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Romance</fullName>
            </value>
            <value>
                <fullName>Thriller</fullName>
            </value>
            <value>
                <fullName>Children</fullName>
            </value>
            <value>
                <fullName>Sci-Fi</fullName>
            </value>
            <value>
                <fullName>Politics</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CFS_Item__c/fields/CFS_Inventory_Count__c.field-meta.xml
<CustomField>
    <fullName>CFS_Inventory_Count__c</fullName>
    <label>Total Inventory Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CFS_Item__c/fields/CFS_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>CFS_Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CFS_Item__c/fields/CFS_Purchase_Price__c.field-meta.xml
<CustomField>
    <fullName>CFS_Purchase_Price__c</fullName>
    <label>Purchase Price</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CFS_Item__c/fields/Currently_Borrowed__c.field-meta.xml
<CustomField>
    <fullName>Currently_Borrowed__c</fullName>
    <label>Currently Borrowed</label>
    <summaryFilterItems>
        <field>CMS_Customer_Item__c.Status__c</field>
        <operation>equals</operation>
        <value>Borrow</value>
    </summaryFilterItems>
    <summaryForeignKey>CMS_Customer_Item__c.CSF_Item__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/CFS_Item__c/fields/Discount_Category__c.field-meta.xml
<CustomField>
    <fullName>Discount_Category__c</fullName>
    <label>Discount Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CFS_Item__c/fields/Total_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Total_Revenue__c</fullName>
    <label>Total Revenue</label>
    <summarizedField>CMS_Customer_Item__c.Borrowed_Price__c</summarizedField>
    <summaryForeignKey>CMS_Customer_Item__c.CSF_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/CFS_Item__c/fields/Units_Available__c.field-meta.xml
<CustomField>
    <fullName>Units_Available__c</fullName>
    <formula>CFS_Inventory_Count__c -  Currently_Borrowed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Units Available</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CFS_Item__c/fields/Video_Director__c.field-meta.xml
<CustomField>
    <fullName>Video_Director__c</fullName>
    <label>Video Director</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFS_Item__c/fields/Video_Name__c.field-meta.xml
<CustomField>
    <fullName>Video_Name__c</fullName>
    <label>Video Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFS_Item__c/fields/Video_Publication__c.field-meta.xml
<CustomField>
    <fullName>Video_Publication__c</fullName>
    <label>Video Publication</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFS_Item__c/recordTypes/CFS_AVEquipment.recordType-meta.xml
<RecordType>
    <fullName>CFS_AVEquipment</fullName>
    <active>true</active>
    <description>This type of record holds information on items present in the library which are sold as CD/DVDs.</description>
    <label>AV Equipment</label>
</RecordType>

force-app/main/default/objects/CFS_Item__c/recordTypes/CFS_Book.recordType-meta.xml
<RecordType>
    <fullName>CFS_Book</fullName>
    <active>true</active>
    <description>This type of record holds information on items present in the library which are sold as books.</description>
    <label>Book</label>
</RecordType>

force-app/main/default/objects/CMS_Customer_Item__c/CMS_Customer_Item__c.object-meta.xml
<CustomObject>
    <label>Customer Item</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Customer Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CMS_Customer_Item__c/fields/Borrowed_Price__c.field-meta.xml
<CustomField>
    <fullName>Borrowed_Price__c</fullName>
    <label>Borrowed Price</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CMS_Customer_Item__c/fields/CSF_Customer__c.field-meta.xml
<CustomField>
    <fullName>CSF_Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>CFS_Customer__c</referenceTo>
    <relationshipLabel>Customer Items</relationshipLabel>
    <relationshipName>Customer_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CMS_Customer_Item__c/fields/CSF_Item__c.field-meta.xml
<CustomField>
    <fullName>CSF_Item__c</fullName>
    <label>Item</label>
    <referenceTo>CFS_Item__c</referenceTo>
    <relationshipLabel>Customer Items</relationshipLabel>
    <relationshipName>Customer_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CMS_Customer_Item__c/fields/Item_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Code__c</fullName>
    <label>Item Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CMS_Customer_Item__c/fields/Item_s_Purchase_Price__c.field-meta.xml
<CustomField>
    <fullName>Item_s_Purchase_Price__c</fullName>
    <label>Item&apos;s Purchase Price</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CMS_Customer_Item__c/fields/Item_type__c.field-meta.xml
<CustomField>
    <fullName>Item_type__c</fullName>
    <label>Item type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Book</fullName>
            </value>
            <value>
                <fullName>AV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CMS_Customer_Item__c/fields/Late_Fees__c.field-meta.xml
<CustomField>
    <fullName>Late_Fees__c</fullName>
    <formula>IF (
     ISPICKVAL(Status__c, &apos;Borrow&apos;) &amp;&amp; TODAY() &gt; End_Date__c,
				 (TODAY() - End_Date__c)*0,
				 0
				)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Late Fees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CMS_Customer_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrow</fullName>
                <default>true</default>
                <label>Borrow</label>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Check out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item_wise_Matrix__mdt/Item_wise_Matrix__mdt.object-meta.xml
<CustomObject>
    <label>Item wise Matrix</label>
    <pluralLabel>Item wise Matrix</pluralLabel>
</CustomObject>

force-app/main/default/objects/Item_wise_Matrix__mdt/fields/Borrowing_rate_per_Day__c.field-meta.xml
<CustomField>
    <fullName>Borrowing_rate_per_Day__c</fullName>
    <label>Borrowing rate per day</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item_wise_Matrix__mdt/fields/Concurrent_Borrowing_limit__c.field-meta.xml
<CustomField>
    <fullName>Concurrent_Borrowing_limit__c</fullName>
    <label>Concurrent Borrowing limit</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ItemSearchController.cls
/*
@Author : Mehul Jain
@Date : 17/11/2109
@Description : Server side controller for the Item search component.
*/

public class ItemSearchController {
     
    //Return the result list of items using filters on search area
    @AuraEnabled
    Public static List<CFS_Item__c> getItemList( String strKeyword, String strType, String strCategory ){
        List<CFS_Item__c> lstItem ;
        try {
            //Create matcher string
            String strSearch = '%' + strKeyWord + '%';
            //Book and AV Record type developer names
            String strBookRT = 'CFS_Book';
            String strAVRT = 'CFS_AVEquipment';
            String strQuery = 'SELECT Id, Name, CurrencyIsoCode, RecordTypeId, CFS_Category__c, CFS_Is_Active__c,' + 
                               'CFS_Inventory_Count__c, CFS_Purchase_Price__c, Discount_Category__c, Total_Revenue__c,'+ 
                               'Currently_Borrowed__c, Units_Available__c, Book_name__c, Book_Author__c, Book_Publication__c,'+ 
                               'Video_Name__c, Video_Publication__c, Video_Director__c '+ 
                               'FROM CFS_Item__c';
                               
            //building dynamic query based on Category and Item type chosen
            if (strType == 'Books') {
                strQuery += ' where recordtype.developername = :strBookRT';
                if ( strKeyword != null ) {
                    strQuery += ' and (Book_name__c like :strSearch OR Book_Author__c like :strSearch OR Book_Publication__c like :strSearch) ';
                }
                
            } else {
                strQuery += ' where recordtype.developername = :strAVRT';
                if ( strKeyword != null ) {
                    strQuery += ' and (Video_Name__c like :strSearch OR Video_Publication__c like :strSearch OR Video_Director__c like :strSearch) ';
                }
            }
            //Adding category to the where clause
            if ( strCategory != '') {
                    strQuery += ' and CFS_Category__c = :strCategory';
            }
            system.debug('@@strQuery' + strQuery);
            
            //Fetch list of items by making DML
            lstItem = Database.Query(strQuery); 
            
        } catch (Exception e) {
            createErrorLogs('ItemSearchController', 'getItemList', e.getMessage() + ' : ' + e.getStackTraceString());
        }
        return lstItem;
    }
    
    //Create Customer Item junction records and transfer to client side controller
    @AuraEnabled
    public static List<CMS_Customer_Item__c> createCI(string lstids, Id customerId) {
        List<CMS_Customer_Item__c> lstCustItem = new List<CMS_Customer_Item__c>();
        try {
            List<string> lstItemIds = (List<string>) JSON.deserialize(lstids, List<string>.class);
            List<CFS_Item__c> lstCI = new List<CFS_Item__c>();
            Map<String, Integer> mapRTToLimit = new Map<String, Integer>();
            CMS_Customer_Item__c objCustItem ; 
            
            //Fetch the customer details
            List<CFS_Customer__c> lstCFS = [Select Id, Email__c from CFS_Customer__c where Id =: customerId];
            //Fetch list based on Item sfdcid or Item Name for rapid checkout
            lstCI = [Select Id,Name,Currently_Borrowed__c,CFS_Purchase_Price__c,Book_name__c,Video_Name__c,Discount_Category__c,Units_Available__c,RecordType.Developername
                     from CFS_Item__c 
                     where Id IN: lstItemIds OR Name IN: lstItemIds];
                     
                                                          
            List<Item_wise_Matrix__mdt> lstItemMatrix = [Select MasterLabel,Borrowing_rate_per_Day__c,Concurrent_Borrowing_limit__c
                                                         from Item_wise_Matrix__mdt]; 
            //Creating map of Item based matrix
            for ( Item_wise_Matrix__mdt objMatrix : lstItemMatrix ) {
                mapRTToLimit.put(objMatrix.MasterLabel,Integer.valueOf(objMatrix.Borrowing_rate_per_Day__c));
            }          
            //Map the customer item fields from Parent Item field        
            for ( CFS_Item__c objCI : lstCI ) {
                objCustItem = new CMS_Customer_Item__c();
                objCustItem.End_Date__c = system.today().addDays(30);
                objCustItem.Start_Date__c = system.today();
                objCustItem.CSF_Customer__c = customerId;
                objCustItem.CSF_Item__c = objCI.Id;
                //Borrowed price kept at 2 per day for AV and 1 per day for Books
                objCustItem.Borrowed_Price__c = mapRTToLimit.get(objCI.RecordType.Developername)*30 ;
                objCustItem.Item_s_Purchase_Price__c = objCI.CFS_Purchase_Price__c;
                objCustItem.Item_type__c= objCI.RecordType.Developername.containsIgnoreCase('BOOK') ? 'Book' : 'AV' ;
                objCustItem.Item_Name__c = objCI.RecordType.Developername.containsIgnoreCase('BOOK') ? objCI.Book_name__c  : objCI.Video_Name__c; 
                objCustItem.Customer_Email__c = lstCFS[0].Email__c;
                objCustItem.Item_Code__c = objCI.Name;
                lstCustItem.add(objCustItem);
            }    
               
        } catch (Exception e) {
            createErrorLogs('ItemSearchController', 'createCI', e.getMessage() + ' : ' + e.getStackTraceString());
        }   
        
        return lstCustItem;   
    }
    
    //Insert the final customer Item records into Salesforce Database
    @AuraEnabled
    public static String insertCI (String lstCI) {
        List<CMS_Customer_Item__c > lstToInsert = new List<CMS_Customer_Item__c>();
        system.debug('@@lstToInsert' + lstToInsert);
        try {
            lstToInsert= (List<CMS_Customer_Item__c >) JSON.deserialize(lstCI, List<CMS_Customer_Item__c >.class);
            insert lstToInsert;
        }catch (Exception e) {
            createErrorLogs('ItemSearchController', 'insertCI', e.getMessage() + ' : ' + e.getStackTraceString());
        }
        return 'Success';
    }
    
    //Calculate the total late fee for current customer
    @AuraEnabled
    public static Integer calculateLateFee(String customerId) {
        Decimal intTotalLateFee = 0;
        try {
            //Fetch total late fee for the customer using aggregate query
            List<AggregateResult> lstLateFee = [Select CSF_Customer__c,SUM(Late_Fees__c) From CMS_Customer_Item__c 
                                                        Where CSF_Customer__c = :customerId
                                                        Group by CSF_Customer__c];
            
            if ( !lstLateFee.isEmpty() ) {
                intTotalLateFee  = (Decimal)lstLateFee[0].get('expr0');
                system.debug('@@intTotalLateFee' + intTotalLateFee);
            }   
        } catch (Exception e) {
            createErrorLogs('ItemSearchController', 'calculateLateFee', e.getMessage() + ' : ' + e.getStackTraceString());
        }
        
        return Integer.valueOf(intTotalLateFee) ;                                       
                                                    
    }
    
    //Validate if the items are currently borrowed by the user or checked out by him
    @AuraEnabled
    public static String verifyItems(String customerId, String strCIList) {
        String strInvalidItems = '';
        try {
            Integer intCurrentBorrowed ;
            Integer intMaxAllowed = Integer.valueOf(Label.Max_Number_of_Items_per_user);
            List<CMS_Customer_Item__c > lstCI = (List<CMS_Customer_Item__c >) JSON.deserialize(strCIList, List<CMS_Customer_Item__c >.class);
            //Fetch list of all checked out or currently borrowed items by the current user
            List<CMS_Customer_Item__c> lstExistingItem = [Select Id, CSF_Item__c ,Status__c,
                                                          CSF_Customer__r.Currently_Borrowed_Items__c,
                                                          CSF_Item__r.Currently_Borrowed__c,
                                                          CSF_Item__r.RecordType.DeveloperName
                                                          from CMS_Customer_Item__c 
                                                          where CSF_Customer__c =: customerId and 
                                                          (Status__c = 'Check out' OR Status__c = 'Borrow')];
                                                                                              
            Set<String> setCheckedOutItems = new Set<String>();
            if ( !lstExistingItem.isEmpty()) {
                intCurrentBorrowed = (Integer)lstExistingItem[0].CSF_Customer__r.Currently_Borrowed_Items__c;
                //Set of existing item ids
                for (CMS_Customer_Item__c objCI : lstExistingItem ) {
                    setCheckedOutItems.add(objCI.CSF_Item__c);
                }           
                
                for (CMS_Customer_Item__c objCI : lstCI) {
                    //Checking if the shopping cart contains any of the existing item ids
                    if (setCheckedOutItems.contains(objCI.CSF_Item__c)){
                        strInvalidItems += objCI.Item_Name__c + ', ';
                    }
                    
                } 
                //Removing last occurence of comma                                   
                strInvalidItems = strInvalidItems.substringBeforeLast(',');
                
            
                if ( strInvalidItems != '' ) {
                    return 'Please remove the following items since you already have checked them out or currently borrowed : '+strInvalidItems;
                } else if ( lstCI.size() + intCurrentBorrowed  > intMaxAllowed  ) {
                    Integer intRowsToRemove = lstCI.size() + intCurrentBorrowed  - intMaxAllowed ;
                    return 'Please remove at least '+intRowsToRemove+' rows to proceed since you already have '+intCurrentBorrowed +' items currently brrowed. Maximum borrow limit per person is '+intMaxAllowed +'.';
                } else {
                    return '';
                }
            } 
        
        } catch (Exception e) {
            createErrorLogs('ItemSearchController', 'verifyItems', e.getMessage() + ' : ' + e.getStackTraceString());
        } 
        return '';   
        
    }
    
    @AuraEnabled
    public static Map<String, String> fetchCategories(){
        Map<String, String> options = new Map<String, String>();
        Schema.DescribeFieldResult fieldResult = CFS_Item__c.CFS_Category__c.getDescribe();
        List<Schema.PicklistEntry> objPL = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry p:objPL){
        	options.put(p.getValue(), p.getLabel());
        } 
        return options;
    } 
    
    public static void createErrorLogs(String strClassName, String strMethodName, String strErrorMessage) {
        CFS_Error_Log__c objError = new CFS_Error_Log__c();
        objError.Class_Name__c = strClassName;
        objError.Method_Name__c = strMethodName;
        objError.Error_Message__c = strErrorMessage;
        objError.Type__c = 'Code Exception';
        
        Database.insert(objError);
        
    }
}