force-app/main/default/objects/CFS_Customer__c/CFS_Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CFS_Item__c/CFS_Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CFS_Item__c/fields/Book_name__c.field-meta.xml
<CustomField>
    <fullName>Book_name__c</fullName>
    <label>Book name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFS_Item__c/fields/Video_Name__c.field-meta.xml
<CustomField>
    <fullName>Video_Name__c</fullName>
    <label>Video Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFS_Item__c/recordTypes/CFS_AVEquipment.recordType-meta.xml
<RecordType>
    <fullName>CFS_AVEquipment</fullName>
    <active>true</active>
    <description>This type of record holds information on items present in the library which are sold as CD/DVDs.</description>
    <label>AV Equipment</label>
</RecordType>

force-app/main/default/objects/CFS_Item__c/recordTypes/CFS_Book.recordType-meta.xml
<RecordType>
    <fullName>CFS_Book</fullName>
    <active>true</active>
    <description>This type of record holds information on items present in the library which are sold as books.</description>
    <label>Book</label>
</RecordType>

force-app/main/default/objects/CMS_Customer_Item__c/CMS_Customer_Item__c.object-meta.xml
<CustomObject>
    <label>Customer Item</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Customer Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/TestItemSearchController.cls
/*
@Author : Mehul Jain
@Date : 17/11/2109
@Description : Test class for the Server side controller for the Item search component.
*/

@IsTest
public class TestItemSearchController {
    private static CFS_Item__c objItem1;
    private static CFS_Item__c objItem2;
    private static CFS_Customer__c objCustomer;
    
    public static testmethod void testCase1(){
        createData();
        Test.startTest();
        List<CMS_Customer_Item__c> lstCI = new List<CMS_Customer_Item__c>();
        ItemSearchController.getItemList('Test', 'Books', '');
        ItemSearchController.getItemList('Test', 'AV', '');
        lstCI = ItemSearchController.createCI(JSON.serialize(new List<String>{objItem1.Id, objItem2.Id}), objCustomer.id);
        ItemSearchController.calculateLateFee(String.valueOf(objCustomer.Id));
        ItemSearchController.verifyItems(objCustomer.Id, JSON.serialize(lstCI));
        ItemSearchController.insertCI(JSON.serialize(lstCI));
        ItemSearchController.insertCI(JSON.serialize(new List<String>{'test1', 'test2'}));
        ItemSearchController.fetchCategories();
        List<CMS_Customer_Item__c> lstCustItem = [select id from CMS_Customer_Item__c ];
        system.assert(lstCustItem.size() > 0);
        Test.stopTest();
    }
    
    public static void createData () {
        Id idRTBook =  Schema.SObjectType.CFS_Item__c.getRecordTypeInfosByDeveloperName().get('CFS_Book').getRecordTypeId();
        Id idRTAV =  Schema.SObjectType.CFS_Item__c.getRecordTypeInfosByDeveloperName().get('CFS_AVEquipment').getRecordTypeId();
        List<CFS_Item__c> lstItem = new List<CFS_Item__c >();
        objItem1 = new CFS_Item__c();
        objItem1.Recordtypeid = idRTBook;
        objItem1.Book_Name__c = 'Test Book1';
        
        objItem2 = new CFS_Item__c();
        objItem2.Recordtypeid = idRTAV;
        objItem2.Video_Name__c = 'Test Video1';
        lstItem.add(objItem1);
        lstItem.add(objItem2);
        
        insert lstItem;
        
        
        objCustomer = new CFS_Customer__c();
        objCustomer.Name = 'Test User';
        objCustomer.Email__c = 'test@test.com';
        objCustomer.Mobile__c = '9999800887';
        
        insert objCustomer;
    }
}