force-app/main/default/objects/CFS_Customer__c/CFS_Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CFS_Item__c/CFS_Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CFS_Item__c/fields/Book_Author__c.field-meta.xml
<CustomField>
    <fullName>Book_Author__c</fullName>
    <label>Book Author</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFS_Item__c/fields/Book_name__c.field-meta.xml
<CustomField>
    <fullName>Book_name__c</fullName>
    <label>Book name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFS_Item__c/fields/Book_Publication__c.field-meta.xml
<CustomField>
    <fullName>Book_Publication__c</fullName>
    <label>Book Publication</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CMS_Customer_Item__c/CMS_Customer_Item__c.object-meta.xml
<CustomObject>
    <label>Customer Item</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Customer Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CMS_Customer_Item__c/fields/CSF_Customer__c.field-meta.xml
<CustomField>
    <fullName>CSF_Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>CFS_Customer__c</referenceTo>
    <relationshipLabel>Customer Items</relationshipLabel>
    <relationshipName>Customer_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CMS_Customer_Item__c/fields/CSF_Item__c.field-meta.xml
<CustomField>
    <fullName>CSF_Item__c</fullName>
    <label>Item</label>
    <referenceTo>CFS_Item__c</referenceTo>
    <relationshipLabel>Customer Items</relationshipLabel>
    <relationshipName>Customer_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CMS_Customer_Item__c/fields/Item_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Code__c</fullName>
    <label>Item Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CMS_Customer_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrow</fullName>
                <default>true</default>
                <label>Borrow</label>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Check out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ItemBuyerController.cls
public with sharing class ItemBuyerController {
    @AuraEnabled(cacheable=true)
    public static List<CFS_Item__c> getItems(){
        List<CFS_Item__c> lstItem = [Select Id, Name, 
                                    Book_Author__c, Book_name__c,Book_Publication__c
                                    FROM CFS_Item__c 
                                    Where Book_name__c != null 
                                    Limit 10];
        return lstItem;                            
    }
    
    @AuraEnabled(cacheable=true)
    public static List<CMS_Customer_Item__c> getCustItems(String strItemId){
        system.debug('@strItemId' + strItemId);
        List<CMS_Customer_Item__c> lstItem = [Select Id, Name, CSF_Customer__r.Name, 
                                    Item_Code__c, Status__c,CSF_Customer__r.Id
                                    FROM CMS_Customer_Item__c 
                                    Where CSF_Item__c =: strItemId 
                                    Limit 10];
        return lstItem;                            
    }
}