force-app/main/default/objects/CFS_Error_Log__c/CFS_Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{0000}</displayFormat>
        <label>Error Logging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CFS_Error_Log__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Queueable2.cls
public class Queueable2 implements Queueable,Database.AllowsCallouts {
    public void execute(QueueableContext context) {
        // Your processing logic here 
        Http http = new Http();  
        String requestBody = '{"name":"test","salary":"123","age":"23"}';      
        HttpRequest req = new HttpRequest();
        req.setEndpoint('http://dummy.restapiexample.com/api/v1/create');
        req.setHeader('Content-Type', 'application/json');
        req.setMethod('POST');
        req.setBody(requestBody);
        
        HttpResponse response = http.send(req);
        system.debug('@@response for Q2' +response.getBody()  );
        CFS_Error_Log__c obj = new CFS_Error_Log__c();
        obj.Request__c = 'test2';
        obj.Response__c = 'test2';
        insert obj;
        
    }
}